import type { Column, Diagram, Relationship } from "#/types/diagram";

const TS_NUM = new Set([
  "tinyint",
  "smallint",
  "mediumint",
  "int",
  "integer",
  "bigint",
  "smallserial",
  "serial",
  "bigserial",
  "decimal",
  "numeric",
  "float",
  "double",
  "real",
  "money",
  "smallmoney",
  "number",
  "long",
  "double precision",
  "decimal128",
  "year",
]);

const TS_STR = new Set([
  "char",
  "character",
  "varchar",
  "character varying",
  "nchar",
  "nvarchar",
  "text",
  "tinytext",
  "mediumtext",
  "longtext",
  "ntext",
  "string",
  "name",
  "uuid",
  "uniqueidentifier",
  "objectid",
  "inet",
  "cidr",
  "macaddr",
  "enum",
  "set",
  "sql_variant",
  "rowversion",
]);

const TS_BOOL = new Set(["boolean", "bit", "bool"]);

const TS_DATE = new Set([
  "date",
  "time",
  "timestamp",
  "timestamptz",
  "datetime",
  "datetime2",
  "smalldatetime",
  "datetimeoffset",
  "interval",
]);

const TS_JSON = new Set([
  "json",
  "jsonb",
  "object",
  "mixed",
  "map",
  "xml",
  "geometry",
  "regex",
]);

const TS_BINARY = new Set([
  "binary",
  "varbinary",
  "tinyblob",
  "blob",
  "mediumblob",
  "longblob",
  "bytea",
  "image",
]);

export function pascalCase(name: string): string {
  const words = name.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  if (words.length === 0) return "Type";
  return words.map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("");
}

export function tsTypeFor(diagram: Diagram, col: Column): string {
  const base = col.type.toLowerCase();

  let t: string;
  if (col.enumValues && col.enumValues.length > 0) {
    t = col.enumValues.map((v) => JSON.stringify(v)).join(" | ");
  } else if (TS_BOOL.has(base)) {
    t = "boolean";
  } else if (TS_NUM.has(base)) {
    t = "number";
  } else if (TS_DATE.has(base)) {
    t = "Date";
  } else if (TS_JSON.has(base)) {
    t = "Record<string, unknown>";
  } else if (TS_BINARY.has(base)) {
    t = "Buffer";
  } else if (TS_STR.has(base)) {
    t = "string";
  } else {
    t = "unknown";
  }

  if (col.isArray) t += "[]";

  if (diagram.driver === "mongodb" && col.keyType === "primary" && /^id$/i.test(col.name)) {
    t = "string";
  }

  return t;
}

function camelCase(name: string): string {
  const words = name.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  if (words.length === 0) return name;
  const first = words[0];
  return (
    first.charAt(0).toLowerCase() +
    first.slice(1) +
    words.slice(1).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("")
  );
}

function referenceName(rel: Relationship, diagram: Diagram): string {
  const src = diagram.tables.find((t) => t.id === rel.sourceTableId);
  const tgt = diagram.tables.find((t) => t.id === rel.targetTableId);
  const col = src?.columns.find((c) => c.id === rel.sourceColumnId);
  if (col) {
    let n = col.name;
    if (/_id$/i.test(n)) n = n.replace(/_id$/i, "");
    else if (/Id$/.test(n)) n = n.slice(0, -2);
    const cleaned = camelCase(n);
    if (cleaned) return cleaned;
  }
  return tgt ? camelCase(tgt.name) : "reference";
}

export function generateTsTypes(diagram: Diagram): string {
  const header = [
    "// Generated by SchemaCanvas. Do not edit by hand.",
    `// Driver: ${diagram.driver}`,
    diagram.description ? `// ${diagram.description.split("\n").map((l) => `// ${l}`).join("\n")}` : "",
    "",
  ]
    .filter(Boolean)
    .join("\n");

  if (diagram.tables.length === 0) {
    return `${header}// (empty diagram)`;
  }

  const typeNameById = new Map<string, string>();
  for (const t of diagram.tables) typeNameById.set(t.id, pascalCase(t.name));

  const blocks: string[] = [];
  for (const table of diagram.tables) {
    const typeName = typeNameById.get(table.id)!;
    const fields: string[] = [];
    const used = new Set<string>();

    const cols = [...table.columns].sort((a, b) => a.order - b.order);
    for (const c of cols) {
      const name = c.name || "unnamed";
      const t = tsTypeFor(diagram, c);
      fields.push(`  ${name}: ${t}${c.nullable ? " | null" : ""};`);
      used.add(name);
    }

    const outgoing = diagram.relationships.filter((r) => r.sourceTableId === table.id);
    for (const rel of outgoing) {
      const tgt = diagram.tables.find((t) => t.id === rel.targetTableId);
      if (!tgt) continue;
      const targetType = typeNameById.get(tgt.id)!;
      let name = referenceName(rel, diagram);
      if (used.has(name)) name += "Ref";
      used.add(name);
      const srcCol = table.columns.find((c) => c.id === rel.sourceColumnId);
      fields.push(`  ${name}?: ${targetType}${srcCol && srcCol.nullable ? " | null" : ""};`);
    }

    blocks.push(`export type ${typeName} = {\n${fields.join("\n")}\n}`);
  }

  return `${header}\n${blocks.join("\n\n")}\n`;
}
